### ISSUE TITLE
Include lldb_sys as a re-export

### ISSUE THREAD

**Issue by whitfin** [endoli/lldb.rs#25]
Given the tight coupling between this library and the `lldb_sys` crate, perhaps it would be a good idea to add a public re-export of the `lldb_sys` crate?

As it stands, I grabbed the latest version of both `0.0.10` and `0.0.29`, and they don't work together so I had to drop to `0.0.27`, but if we export `lldb_sys` as `sys` we can avoid people having to pull the `lldb_sys` crate manually.

**Comment by waywardmonkeys** [comment]
that seems like it might be worthwhile. I have changes locally that I was still working on for `lldb` to use current `lldb-sys`, but I didn't think anyone was using this at this point.

I'll publish it shortly, I think.

What do you use the sys crate for in terms of things that don't yet have bindings?

**Comment by waywardmonkeys** [comment]
I've published `lldb` version `0.0.11` which works with the current `lldb-sys`. It also re-exports `lldb-sys` as `sys`.

I'd love to hear about what you're doing with it all though.

**Comment by whitfin** [comment]
@waywardmonkeys that's awesome, thanks!

My use case is running `*.dsym` files through for Apple crash reporting, the API I specifically use is:

`SBDebuggerCreateTargetWithFileAndArch`

Which is the equivalent of: `lldb -arch <arch> <symbol>`. 

It might be there's a better way to do this, this code is from a few years ago!

**Comment by waywardmonkeys** [comment]
Does this work if you use the version with a target triple and host platform as well, which is wrapped as `SBDebugger::create_target()` in this crate?

**Comment by waywardmonkeys** [comment]
Fixed in 0.0.11.
