### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by waywardmonkeys** [endoli/lldb.rs#4]
I've not yet tried to build any of this on Linux. First, we'll have to get `lldb-sys.rs` building on Linux ...

**Comment by SlNPacifist** [comment]
The only thing that prevents usage of this on Linux is `build.rs`. Is there a reason for `build.rs` being here?

**Comment by waywardmonkeys** [comment]
I've updated and published the new `lldb-sys.rs` and fixed how linking is configured over there for macOS and now this `build.rs` is in fact no longer needed.

I've removed it and published a new version of `lldb`.

Thanks!

**Comment by dzfranklin** [comment]
This works on my linux machine. Is this no longer an issue?

**Comment by waywardmonkeys** [comment]
Yes, this has been addressed.
